# Generated by Django 4.0.3 on 2022-05-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hobby',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
